version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3020:3020'
    restart: unless-stopped
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/static:/frontend/static
    depends_on:
      - backend
