version: '3.3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3020:3020'
    volumes:
      - ./backend/model/:/backend/model/
    restart: unless-stopped

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  nginx:
    container_name: nginx-container
    build:
      context: ./nginx
    depends_on:
      - frontend
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./keys/translate-bur.key:/etc/nginx/translate-bur.key
      - ./keys/translate-bur.crt:/etc/nginx/translate-bur.crt
    ports:
      - '443:443'
      - '80:80'
