name: Deploy translator
on:
  push:
    branches: ["prod"]
jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Update project
        working-directory: /home/translator
        run: git pull
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        working-directory: /home/translator
        run: docker-compose up -d --build