name: Deploy translator
on:
  push:
    branches: ["master"]
jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Switch to project dir
        run: cd /home/translator
      - name: Update project
        run: git pull
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose up -d --build